### ISSUE TITLE
Show just selected months

### ISSUE THREAD

**Issue by BabaMasha** [brunorosilva/plotly-calplot#19]
Hi, great plot!

Would it be possible to add the feature of showing just few months instead of Jan-Dec? For example only Mar-Aug.

Like in july (https://github.com/e-hulten/july)

Best,
Maryna

**Comment by brunorosilva** [comment]
Hi, Maryna

Do you think something like this suits your purpose?
![image](https://user-images.githubusercontent.com/17326742/227133556-6ede04f6-043d-426c-a3c3-f69b0046848d.png)

Of course it'd be responsive with adjustable width
![image](https://user-images.githubusercontent.com/17326742/227133812-ac3cfe13-df49-40f3-89c4-1244b34d912e.png)

**Comment by BabaMasha** [comment]
Hi Bruno,

Yes this would be perfect, thanks a lot!

Greetings,
Maryna

**Comment by brunorosilva** [comment]
Great, I'll be adding it in the next release. I'm just wrapping up some CI/CD details and input validations.

The code will look like this
```python
import numpy as np
import pandas as pd

from plotly_calplot.calplot import calplot, month_calplot

# mock setup
dummy_start_date = "2019-01-01"
dummy_end_date = "2022-10-03"
dummy_df = pd.DataFrame(
    {
        "ds": pd.date_range(dummy_start_date, dummy_end_date),
        "value": np.random.randint(
            -10,
            30,
            (pd.to_datetime(dummy_end_date) - pd.to_datetime(dummy_start_date)).days
            + 1,
        ),
    }
)
fig1 = calplot(
    dummy_df,
    x="ds",
    y="value",
    showscale=True,
    start_month=3,
    end_month=10
)
```

![image](https://user-images.githubusercontent.com/17326742/227229787-cb83884b-a78b-444a-b90a-45669afc0c91.png)
