### ISSUE TITLE
Troubles with time input

### ISSUE THREAD

**Issue by annariley** [brunorosilva/plotly-calplot#26]
I just just calplot in a dash app and I love it! 

However, I had to spend some time debugging my time values because I couldn't find any documentation on what form the datetimes need to be in. For me, I had to remove my time values and timezone sensitivity in my time column to get my calplot to work properly: 

`df['start_date'] = df['start_date'].apply(lambda row : row.split('T')[0])
  df['start_date'] = pd.to_datetime(df['start_date']).dt.tz_localize(None)`

It might be worth it to include more details about time value specifications in your docs. Thanks!

**Comment by brunorosilva** [comment]
Thanks for the feedback and for using the lib.

The whole lib is actually poorly documented and this is a barrier to entry. I'll get to this as soon as I'm able to.
