### ISSUE TITLE
Dependent on pandas version <2.0.0

### ISSUE THREAD

**Issue by tamidodo** [brunorosilva/plotly-calplot#27]
Is there any way this could be updated to be compatible with newer releases of pandas?

**Comment by brunorosilva** [comment]
Hi Tammy, could you post the error you're getting?
As far as I'm aware, there are not supposed to be any issues with any pandas version above `1.0.5`.

**Comment by tamidodo** [comment]
<img width="808" alt="Screenshot 2023-06-27 at 1 12 01 PM" src="https://github.com/brunorosilva/plotly-calplot/assets/61042740/f324b65f-9c91-43a3-9f0a-03307960b175">

**Comment by tamidodo** [comment]
So if I pip install pandas 2.0.2 it throws that error about plotly-calplot requiring pandas<2.0.0 and if I pip install plotly-calplot after pandas, it uninstalls the version of pandas I have and installs it's own version of pandas (1.5.3):
<img width="810" alt="Screenshot 2023-06-27 at 1 13 10 PM" src="https://github.com/brunorosilva/plotly-calplot/assets/61042740/7e4a490d-f810-40d3-9e81-e012c18b3ea8">

**Comment by brunorosilva** [comment]
@tamidodo thanks so much, I wasn't aware of it. I'll find a fix.
Meanwhile I'd suggest you to use conda, poetry or venv so that you can install plotly_calplot and use pandas < 2.0.0 in a isolated environment (without uninstalling pandas 2.0.2 from your default env).

I'm a fan of poetry as it handles lib versioning, the commands would look like
```bash
pip install poetry
poetry init
```
config for your project and a pyproject.toml will be created
```bash
poetry add plotly-calplot pandas
```
by default it uses pypi as a host, but if your company has a custom lib repo you can change it

**Comment by brunorosilva** [comment]
Hi, @tamidodo 

Did you try installing the libs in the inverse order? first plotly-calplot then pandas?

I've created a notebook showcasing it. [Here's](https://gist.github.com/brunorosilva/0de3f673ba347cea22c0afcf75a626b8) a gist for it.

**Comment by tamidodo** [comment]
To be clear, I have ways of getting around the installation and automatic uninstalling, I'm mostly just adding this issue to document it in case it's something that can be fixed in the package because as a user, you have to know about the issue to implement workarounds which just seemed a little janky.

**Comment by jcbloch** [comment]
+1 on updating to pandas 2
FWIW, I think this will get the job done (didn't create a PR; didn't build, didn't bump version, etc)
https://github.com/AuDigent/plotly-calplot

**Comment by rileywiley** [comment]
> To be clear, I have ways of getting around the installation and automatic uninstalling, I'm mostly just adding this issue to document it in case it's something that can be fixed in the package because as a user, you have to know about the issue to implement workarounds which just seemed a little janky.

How did you get around the issue? The rest of my app is dependent on Pandas 2 so I don't want to go downgrade.

**Comment by jcbloch** [comment]
please see the fork.

https://github.com/brunorosilva/plotly-calplot/compare/main...AuDigent:plotly-calplot:main

**Comment by shayneoneill** [comment]
Any updates on this? Its still incompatible with modern pandas.
