### ISSUE TITLE
Years title interaction

### ISSUE THREAD

**Issue by ghhar98** [brunorosilva/plotly-calplot#3]
Hi, 
I tried using this package, which I find really useful. My problem is that when I'm making my calendar heatmap, the year label interact with the heatmap above : 

![image](https://user-images.githubusercontent.com/78988892/163093393-aff95036-a143-4e1e-88be-83d22be2a09f.png)

The code I'm using to generate the plot is 

`fig = calplot(
         df_day_count,
         x="date",
         y="count",
         name="Number of events",
        years_title=True
    )`

While my df looks like this : 
![image](https://user-images.githubusercontent.com/78988892/163093615-bd84e770-b73f-4c0c-b93b-57577ad87aad.png)

Thanks.

**Comment by brunorosilva** [comment]
Hey @ghhar98 ,

The spacing between two years is a bit sketchy at times and I'll work on a definite fix, but as a quick fix for your problem, try to use the `space_between_plots` parameter, it's default is 0.08 as this worked ok(ish) on the data I tested.

Here are some examples on how to use it with sample data:

with `space_between_plots = 0.08` (default)
![image](https://user-images.githubusercontent.com/17326742/163250792-1ee57ffc-27fb-4ce1-a757-8613e6a3db3d.png)

with `space_between_plots = 0.12`
![image](https://user-images.githubusercontent.com/17326742/163250843-71216a56-33b8-43c6-bbea-60f4a308c0d0.png)

with `space_between_plots = 0.25`
![image](https://user-images.githubusercontent.com/17326742/163250577-0bdd702d-8bfd-442e-a24b-faaee0bd7640.png)

**Comment by ghhar98** [comment]
Thanks for your response, it's now working.
Maybe off subject, but I was also wondering if it currently was possible to add a legend to the plot for the color scale? I can't find an option for it

**Comment by brunorosilva** [comment]
Yes, this is possible. It's not a native option in the library, but you can do it using `update_traces` with the heatmap selector updating the showscale property to `None` or to `True`, as the example below.

```python
fig = calplot(
    dummy_df,
    x="ds",
    y="value",
    years_title=True,
    space_between_plots=0.12,
)
fig.update_traces(showscale=True, selector=dict(type="heatmap"))
```
<img width="775" alt="image" src="https://user-images.githubusercontent.com/17326742/163410123-59daf1d0-699d-4281-9f54-5264c91ea17c.png">

And of course you can add customization to the scale
```python
fig.update_traces(colorbar=dict(
    title="Events per Cell",
    thicknessmode="pixels", thickness=10,
    lenmode="pixels", len=300,
    yanchor="middle",
    ticks="outside", 
    ticksuffix=" events",
    dtick=2
), showscale = True, selector=dict(type='heatmap'))
```
<img width="775" alt="image" src="https://user-images.githubusercontent.com/17326742/163412886-9e457ab3-c6bc-4758-8c62-21804fcf990a.png">

**Comment by brunorosilva** [comment]
@ghhar98 sorry to tag you, but did my response solve your issue?

**Comment by ghhar98** [comment]
Yes, thank you!
