### ISSUE TITLE
Legend with years with different maximum densities 

### ISSUE THREAD

**Issue by ghhar98** [brunorosilva/plotly-calplot#4]
I'm trying to make a calendar heatmap with years with different distributions, and it causes problems with the legend, as one can see in the screenshot. 

![image](https://user-images.githubusercontent.com/78988892/164875754-c722de8f-d596-43e1-a06b-bc0e17bd172f.png)

As we can see, the high density number of event is different depending on the year, which causes problem.

This is the code i'm using : 
![image](https://user-images.githubusercontent.com/78988892/164876681-9d9465d0-502c-4c6b-94a1-f01ee4240f17.png)

Thank you.

**Comment by brunorosilva** [comment]
That's a problem I hadn't think about. Thanks for bringing it up and I'll work on setting a global colorscale as default.

In the meantime you can add `zmin` and `zmax` to set the colorscale values as globals for all years.

If you know what the max and min values possible are, then use
```python
fig.update_traces(
    showscale = True, 
    selector=dict(type='heatmap'),
    zmax=max_possible_value, # like 10 or 20
    zmin=min_possible_value # like zero
)
```

If they vary from user to user user
```python
fig.update_traces(
    showscale = True, 
    selector=dict(type='heatmap'),
    zmax=df["count"].max(),
    zmin=df["count"].min() # or zero
)
```

**Comment by brunorosilva** [comment]
Just published a new version addressing this issue by adding a `colorscale` parameter and forcing the zmax of the colorscale to the global maximum of the dataframe.
